Fix pull new broken by #306
When fixing #306, the pull new command was broken as it wasn't adapted
to use the new _do_update().

This is an example traceback shown by pull new:

Pushing v2.x.x to branch in fork
Creating pull request from branch branch to sociomantic-tsunami/git-hub:v2.x.x
Traceback (most recent call last):
  File "./git-hub", line 2254, in <module>
    main()
  File "./git-hub", line 2246, in main
    args.run(parser, args)
  File "./git-hub", line 683, in check_config_and_run
    cmd.run(parser, args)
  File "./git-hub", line 1574, in run
    IssueCmd.UpdateCmd._do_update(pull['number'], args.labels,
  File "./git-hub", line 1333, in _do_update
    return req.patch(url, **params)
  File "./git-hub", line 525, in <lambda>
    self.json_req(url, method, media_type, *args, **kwargs)
  File "./git-hub", line 490, in json_req
    url = self.base_url + url
TypeError: can only concatenate str (not "int") to str

We revert back to somehow hardcoding the URL used in _do_update()
because some issue/PR metadata can be updated in GH only using the
issues API endpoint.