Always use `config.urltype` inside `git_fetch`
As `urltype` argument is always using `config.urltype`, it
can always be used in the body, no need to pass it as an
argument.

This also fixes this issue:

Traceback (most recent call last):
  File "git-hub", line 1259, in <module>
    class PullUtil (IssueUtil):
  File "git-hub", line 1333, in PullUtil
    def git_fetch(cls, url, ref, urltype=config.urltype):
NameError: name 'config' is not defined